# Generated by Django 6.0.7 on 2026-08-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ibada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mwenyeji', models.CharField(help_text='Mfano: Mzee Joshua au Kijitonyama', max_length=150, verbose_name='Familia Mwenyeji (Host)')),
                ('tarehe_muda', models.DateTimeField(verbose_name='Tarehe na Muda wa Ibada')),
                ('ramani_link', models.URLField(blank=True, help_text='Mfano: https://maps.google.com/?q=...', null=True, verbose_name='Kiungo cha Ramani (Google Maps)')),
                ('maelekezo', models.TextField(blank=True, help_text='Maelekezo mafupi kama: Karibu na Kanisa la Lutheran Sinza', verbose_name='Maelekezo ya kufika')),
                ('masomo', models.TextField(blank=True, help_text='Mfano: Somo la 5 la Kitabu cha Mwongozo wa Kujifunza Biblia', verbose_name='Somo au Mada ya Kujadili')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Ibada Imekamilika?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ibada',
                'verbose_name_plural': 'Ibada za Kanda',
                'ordering': ['-tarehe_muda'],
            },
        ),
        migrations.CreateModel(
            name='Mshiriki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=150, verbose_name='Jina Kamili')),
                ('simu', models.CharField(help_text='Mfano: 0712345678 au 255712345678', max_length=15, verbose_name='Namba ya Simu')),
                ('familia', models.CharField(blank=True, help_text='Mfano: Familia ya Mzee Kamau', max_length=150, verbose_name='Jina la Familia')),
                ('jukumu', models.CharField(choices=[('KIONGOZI', 'Kiongozi wa Kanda'), ('MSHIRIKI', 'Mshiriki wa Kanda')], default='MSHIRIKI', max_length=20, verbose_name='Jukumu')),
                ('is_active', models.BooleanField(default=True, verbose_name='Yuko Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe ya Kusajiliwa')),
            ],
            options={
                'verbose_name': 'Mshiriki',
                'verbose_name_plural': 'Washiriki',
                'ordering': ['jina'],
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='API Key ya SMS (Mfano: Beem API Key)')),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Secret Key / Password ya SMS')),
                ('sender_id', models.CharField(default='KANDA', max_length=20, verbose_name='Sender ID ya SMS')),
                ('sms_template', models.TextField(default='Habari {jina}, ibada yetu ya Kanda ya Sinza & Kijitonyama itafanyika leo Jumapili kwa familia ya {mwenyeji} saa {muda}. Karibu sana! Ramani: {ramani_link}', help_text='Tumia mabano ya {jina}, {mwenyeji}, {muda}, na {ramani_link} ili mfumo uweke taarifa zenyewe kiotomatiki.', verbose_name='Kiolezo cha Ujumbe (SMS Template)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Mfumo wa SMS Uko Active?')),
            ],
            options={
                'verbose_name': 'Mazingira ya SMS (SMS Setting)',
                'verbose_name_plural': 'Mazingira ya SMS (SMS Settings)',
            },
        ),
        migrations.CreateModel(
            name='OmbiLaMaombi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_muombaji', models.CharField(blank=True, help_text='Acha wazi kama unataka maombi yachapishwe kwa jina lako la ushiriki au andika kama unataka yatoke kwa mtu mwingine.', max_length=150, verbose_name='Jina la Muombaji (kama si Mshiriki)')),
                ('aina', models.CharField(choices=[('OMBI', 'Ombi la Sala'), ('SHUSHUDA', 'Shuhuda ya Baraka')], default='OMBI', max_length=10, verbose_name='Aina ya Ujumbe')),
                ('maelezo', models.TextField(verbose_name='Ujumbe wa Ombi au Ushuhuda')),
                ('is_answered', models.BooleanField(default=False, verbose_name='Limejibiwa? (Kwa Shuhuda tu)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarehe na Muda')),
                ('mshiriki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanda.mshiriki', verbose_name='Mshiriki anayeweka')),
            ],
            options={
                'verbose_name': 'Ombi au Ushuhuda',
                'verbose_name_plural': 'Maombi na Shuhuda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Uthibitisho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NITAKUJA', 'Nitakuja'), ('SITAFANIKIWA', 'Sitafanikiwa'), ('NAHITAJI_USAFIRI', 'Nitakuja, Nahitaji Usafiri')], max_length=20, verbose_name='Hali ya Mahudhurio')),
                ('maoni', models.TextField(blank=True, help_text='Mfano: Nitachelewa kidogo au nina wageni 2', null=True, verbose_name='Maelezo/Maoni ya ziada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Muda wa Kujaza')),
                ('ibada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanda.ibada', verbose_name='Ibada')),
                ('mshiriki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanda.mshiriki', verbose_name='Mshiriki')),
            ],
            options={
                'verbose_name': 'Uthibitisho wa Mahudhurio (RSVP)',
                'verbose_name_plural': 'Uthibitisho wa Mahudhurio (RSVPs)',
                'unique_together': {('mshiriki', 'ibada')},
            },
        ),
    ]
