# Generated by Django 6.0.7 on 2026-08-02 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='sms_absent_template',
            field=models.TextField(default='Habari {jina}, tulikumiss sana kwenye ibada ya kanda leo kwa familia ya {mwenyeji}. Tunakuombea na karibu sana tujumuike pamoja Jumapili ijayo!', help_text='Tumia mabano ya {jina} na {mwenyeji}.', verbose_name='Kiolezo cha Wasiofika (Encouragement SMS)'),
        ),
        migrations.AddField(
            model_name='smsconfig',
            name='sms_present_template',
            field=models.TextField(default='Habari {jina}, asante sana kwa kuhudhuria ibada ya kanda leo kwa familia ya {mwenyeji}. Uwepo wako ulikuwa baraka kubwa sana! Ubarikiwe.', help_text='Tumia mabano ya {jina} na {mwenyeji}.', verbose_name='Kiolezo cha Waliopo (Thank You SMS)'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='sms_template',
            field=models.TextField(default='Habari {jina}, ibada yetu ya Kanda ya Sinza & Kijitonyama itafanyika leo Jumapili kwa familia ya {mwenyeji} saa {muda}. Karibu sana! Ramani: {ramani_link}', help_text='Tumia mabano ya {jina}, {mwenyeji}, {muda}, na {ramani_link} ili mfumo uweke taarifa zenyewe kiotomatiki.', verbose_name='Kiolezo cha Mwaliko (SMS Template)'),
        ),
        migrations.CreateModel(
            name='Mahudhurio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False, verbose_name='Alihudhuria?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ibada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanda.ibada', verbose_name='Ibada')),
                ('mshiriki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanda.mshiriki', verbose_name='Mshiriki')),
            ],
            options={
                'verbose_name': 'Mahudhurio',
                'verbose_name_plural': 'Mahudhurio ya Kanda',
                'unique_together': {('ibada', 'mshiriki')},
            },
        ),
    ]
