# Generated by Django 6.0.7 on 2026-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0002_smsconfig_sms_absent_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='leader_passcode',
            field=models.CharField(default='1234', help_text='Neno la siri la kuingia kwenye Dashibodi ya Viongozi', max_length=20, verbose_name='Neno la Siri la Viongozi'),
        ),
    ]
