# Generated by Django 6.0.7 on 2026-08-03 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0003_smsconfig_leader_passcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OmbiLaMaombi',
        ),
    ]
