# Generated by Django 6.0.7 on 2026-08-05 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0004_delete_ombilamaombi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('INVITATION', 'Mwaliko wa Ibada'), ('THANK_YOU', 'Shukrani (Alihudhuria)'), ('ENCOURAGEMENT', 'Faraja (Hakuhudhuria)'), ('REMINDER', 'Kikumbusho cha RSVP')], default='INVITATION', max_length=20, verbose_name='Aina ya SMS')),
                ('status', models.CharField(choices=[('SUCCESS', 'Imefanikiwa'), ('FAILED', 'Imeshindwa'), ('MOCKUP', 'Mockup (Jaribio)')], default='MOCKUP', max_length=20, verbose_name='Hali ya Utumaji')),
                ('phone', models.CharField(max_length=20, verbose_name='Namba ya Simu')),
                ('message', models.TextField(verbose_name='Ujumbe')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Hitilafu (Ikiwa Ipo)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Muda wa Kutumwa')),
                ('ibada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanda.ibada', verbose_name='Ibada')),
                ('mshiriki', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanda.mshiriki', verbose_name='Mshiriki')),
            ],
            options={
                'verbose_name': 'Rekodi ya SMS',
                'verbose_name_plural': 'Kumbukumbu za SMS',
                'ordering': ['-created_at'],
            },
        ),
    ]
