# Generated by Django 5.2 on 2026-08-25 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0006_alter_ibada_id_alter_mahudhurio_id_alter_mshiriki_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mshiriki',
            name='cheo',
            field=models.CharField(blank=True, default='Kiongozi wa Kanda', help_text='Mfano: Mwenyekiti wa Kanda, Mzee wa Kanda, Katibu, n.k.', max_length=100, verbose_name='Cheo / Wadhifa'),
        ),
        migrations.AddField(
            model_name='mshiriki',
            name='picha',
            field=models.ImageField(blank=True, null=True, upload_to='viongozi/', verbose_name='Picha ya Kiongozi / Mshiriki'),
        ),
        migrations.AlterField(
            model_name='ibada',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mahudhurio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mshiriki',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='api_key',
            field=models.CharField(blank=True, help_text='Username ya akaunti yako ya Next SMS au API Key', max_length=255, null=True, verbose_name='Username / API Key ya Next SMS'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='secret_key',
            field=models.CharField(blank=True, help_text='Password ya akaunti ya Next SMS au API Secret', max_length=255, null=True, verbose_name='Password / Secret Key ya Next SMS'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='sender_id',
            field=models.CharField(default='NEXTSMS', help_text='Jina la mtumaji lililoidhinishwa, mfano: NEXTSMS, CHURCH, au KANISA', max_length=20, verbose_name='Sender ID ya SMS'),
        ),
        migrations.AlterField(
            model_name='smslog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='uthibitisho',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
