# Generated by Django 5.2 on 2026-08-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0007_mshiriki_cheo_mshiriki_picha_alter_ibada_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mshiriki',
            name='picha',
            field=models.FileField(blank=True, null=True, upload_to='viongozi/', verbose_name='Picha ya Kiongozi / Mshiriki'),
        ),
    ]
