# Generated by Django 5.2 on 2026-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanda', '0009_seed_official_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username / API Key ya Next SMS'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='secret_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Password / Secret Key ya Next SMS'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='sender_id',
            field=models.CharField(default='IBADA', max_length=20, verbose_name='Sender ID ya SMS'),
        ),
    ]
